version: '3'
services:
  mq:
    image: icr.io/ibm-messaging/mq:latest
    hostname: mq
    container_name: mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
    ports:
      - 1414:1414
      - 9443:9443

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  connect:
        image: kafkaconnect-with-mq-source:1.3.1
        hostname: connect
        container_name: connect
        depends_on:
          - zookeeper
          - broker
          - mq
        ports:
          - 8083:8083
          - 8888:8888
        volumes:
          - ./config:/opt/kafka/config
          - ./logs:/opt/kafka/logs
          - ./plugins:/opt/kafka/plugins
          - ./xsd:/opt/kafka/xsd